version: '3'
services:
  agent1:
    image: olichwiruk/aries-cloudagent
    ports:
      - "${AGENT1_PORT}:${AGENT1_PORT}"
      - "${AGENT1_ADMIN_PORT}:${AGENT1_ADMIN_PORT}"
    environment:
      AGENT_NAME: ${AGENT1_NAME}
      ACAPY_ENDPOINT: http://${VON_HOST}:${AGENT1_PORT}
      ACAPY_HOST: 0.0.0.0
      ACAPY_PORT: ${AGENT1_PORT}
      ACAPY_ADMIN_PORT: ${AGENT1_ADMIN_PORT}
      GENESIS_URL: http://${VON_HOST}:9000/genesis
    networks:
      - von_von

  agent2:
    image: olichwiruk/aries-cloudagent
    ports:
      - "${AGENT2_PORT}:${AGENT2_PORT}"
      - "${AGENT2_ADMIN_PORT}:${AGENT2_ADMIN_PORT}"
    environment:
      AGENT_NAME: ${AGENT2_NAME}
      ACAPY_ENDPOINT: http://${VON_HOST}:${AGENT2_PORT}
      ACAPY_HOST: 0.0.0.0
      ACAPY_PORT: ${AGENT2_PORT}
      ACAPY_ADMIN_PORT: ${AGENT2_ADMIN_PORT}
      GENESIS_URL: http://${VON_HOST}:9000/genesis
    networks:
      - von_von

networks:
  von_von:
    external: true
